### ISSUE TITLE
TypeError: Argument must be a Discord.Client, Discord.ShardingManager, or a string

### ISSUE THREAD

**Issue by mmiszy** [synzen/Discord.RSS#105]
I'm trying to use Discord.RSS with an existing bot but unfortunately it's throwing an error:

My code, straight from readme:

```typescript
import Discord from "discord.js";
import DiscordRSS from "discord.rss";

const client = new Discord.Client();
const drss = new DiscordRSS.Client({ database: { uri: "./sources" } });

client.login(process.env.DISCORD_BOT_TOKEN);
drss.login(client);
```

**Comment by mmiszy** [comment]
Mananged to overcome the issue by using `drss._defineBot(client);` instead

**Comment by synzen** [comment]
Hey there, I just tried it and it seems to be working fine for me. The import statements are odd though - are you trying to use this in a browser?

![image](https://user-images.githubusercontent.com/18688793/57232233-27aa1880-6fea-11e9-8b97-6c142ac52c34.png)

**Comment by mmiszy** [comment]
No, sorry for the confusion! I'm using TypeScript.

Here's generated JS code:

```js
"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const discord_js_1 = __importDefault(require("discord.js"));
const discord_rss_1 = __importDefault(require("discord.rss"));

const client = new discord_js_1.default.Client();
const drss = new discord_rss_1.default.Client({ database: { uri: "./sources" } });

client.login(process.env.DISCORD_BOT_TOKEN);
drss._defineBot(client);
```

**Comment by synzen** [comment]
I see. But I can't seem to reproduce the issue - have you tried it without TS?

**Comment by mmiszy** [comment]
Yes, it's exactly the same.

Error:

```
/…/project/node_modules/discord.rss/structs/Client.js:109
    } else throw new TypeError('Argument must be a Discord.Client, Discord.ShardingManager, or a string')
           ^

TypeError: Argument must be a Discord.Client, Discord.ShardingManager, or a string
    at Client.login (/…/project/node_modules/discord.rss/structs/Client.js:109:18)
    at Object.<anonymous> (/…/project/test.js:9:6)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
```

The exact JS code I tried:

```js
const Discord = require("discord.js");
const DiscordRSS = require("discord.rss");

const client = new Discord.Client();
const drss = new DiscordRSS.Client({ database: { uri: "./sources" } });

// client.login(process.env.DISCORD_BOT_TOKEN);
drss.login(client);
```

**Comment by mmiszy** [comment]
Could it be related to the fact that `discord.js` `require`d by `discord.rss` is, as a matter of fact, imported from different directory? 

```
npm ls discord.js
typeofweb-discord-bot@1.0.0 /Users/michal/htdocs/typeofweb-discord-bot
├── discord.js@11.4.2 
└─┬ discord.rss@4.0.2
  └── discord.js@11.4.2
```

I think it's becasue `discord.js` is a dependency of discord.rss — while it probably should be a `peerDependency`?

**Comment by synzen** [comment]
That *does* seem to be the cause of the issue from a little research - have you tested it and confirmed that it fixed the problem?
