### ISSUE TITLE
TypeError: scheduleList is not iterable

### ISSUE THREAD

**Issue by frozaum** [synzen/Discord.RSS#132]
TypeError: scheduleList is not iterable
    at Function.assignSchedules (C:\Users\eliam\Discord.RSS\src\util\FeedScheduler.js:30:28)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at async Client.start (C:\Users\eliam\Discord.RSS\src\structs\Client.js:214:9)

**Comment by synzen** [comment]
Please be more specific than pasting an error with no context - what branch you used and how you got it for example. If you're getting this error on dev branch, use the master branch instead as the [setup guide] recommends for a more stable version

**Comment by synzen** [comment]
dev branch is currently undergoing a major rewrite, please use master branch instead as the [setup guide](https://github.com/synzen/Discord.RSS/wiki/Setup) recommends for a more stable version

**Comment by Macley-Kun** [comment]
Small note for heroku users:
`2019-12-31T16:45:36.897320+00:00 app[web.1]: fs.js:114
2019-12-31T16:45:36.897341+00:00 app[web.1]:     throw err;
2019-12-31T16:45:36.897342+00:00 app[web.1]:     ^
2019-12-31T16:45:36.897344+00:00 app[web.1]: 
2019-12-31T16:45:36.897347+00:00 app[web.1]: Error: ENOENT: no such file or directory, open '/app/src/package.json'
2019-12-31T16:45:36.897349+00:00 app[web.1]:     at Object.openSync (fs.js:443:3)
2019-12-31T16:45:36.897350+00:00 app[web.1]:     at Object.readFileSync (fs.js:343:35)
2019-12-31T16:45:36.897352+00:00 app[web.1]:     at Object.<anonymous> (/app/src/models/common/Version.js:3:31)
2019-12-31T16:45:36.897353+00:00 app[web.1]:     at Module._compile (internal/modules/cjs/loader.js:778:30)
2019-12-31T16:45:36.897355+00:00 app[web.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2019-12-31T16:45:36.897356+00:00 app[web.1]:     at Module.load (internal/modules/cjs/loader.js:653:32)
2019-12-31T16:45:36.897357+00:00 app[web.1]:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2019-12-31T16:45:36.897358+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2019-12-31T16:45:36.897359+00:00 app[web.1]:     at Module.require (internal/modules/cjs/loader.js:692:17)
2019-12-31T16:45:36.897360+00:00 app[web.1]:     at require (internal/modules/cjs/helpers.js:25:18)
2019-12-31T16:45:36.897361+00:00 app[web.1]:     at Object.<anonymous> (/app/src/models/GuildProfile.js:2:17)
2019-12-31T16:45:36.897362+00:00 app[web.1]:     at Module._compile (internal/modules/cjs/loader.js:778:30)
2019-12-31T16:45:36.897363+00:00 app[web.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
2019-12-31T16:45:36.897365+00:00 app[web.1]:     at Module.load (internal/modules/cjs/loader.js:653:32)
2019-12-31T16:45:36.897366+00:00 app[web.1]:     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
2019-12-31T16:45:36.897367+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
2019-12-31T16:45:36.905295+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2019-12-31T16:45:36.905729+00:00 app[web.1]: npm ERR! errno 1
2019-12-31T16:45:36.907235+00:00 app[web.1]: npm ERR! discord.rss@5.1.0`

Happens just after 5, updated with most recent commit, still same issue sadly.
Workaround is to roll-back for now.

**Comment by synzen** [comment]
It's like I mentioned, dev branch is undergoing a major rewrite so things will unfortunately be breaking - but that particular problem should be fixed now. You can keep track of progress at https://github.com/synzen/Discord.RSS/projects/6

For any new issues that arise, you can make a new issue

**Comment by Macley-Kun** [comment]
Thanks dude! Will test in a bit! Just wanted to let ya know what things we find :p happy 2020
