### ISSUE TITLE
Error: Cannot find module '../../../util/db/schedules.js'

### ISSUE THREAD

**Issue by StrangeRanger** [synzen/Discord.RSS#134]
I'm currently self hosting Discord.RSS on an Ubuntu based server. Recently I followed the guide to try to get the bot to work/have a web interface, but encountered a problem upon starting the bot. This is the problem/error message I got when using `node server.js` (this also happens when trying to run the bot via systemd):
```
user@hostname:~/Discord.RSS$ node server.js
internal/modules/cjs/loader.js:969
    throw err;
    ^

Error: Cannot find module '../../../util/db/schedules.js'
Require stack:
- /home/user/Discord.RSS/src/web/routes/api/cp.js
- /home/user/Discord.RSS/src/web/routes/api/index.js
- /home/user/Discord.RSS/src/web/index.js
- /home/user/Discord.RSS/src/structs/Client.js
- /home/user/Discord.RSS/src/index.js
- /home/user/Discord.RSS/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:17)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/user/Discord.RSS/src/web/routes/api/cp.js:6:24)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/user/Discord.RSS/src/web/routes/api/index.js:7:12)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/user/Discord.RSS/src/web/index.js:12:19)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at new Client (/home/user/Discord.RSS/src/structs/Client.js:33:19)
    at Object.<anonymous> (/home/user/Discord.RSS/server.js:10:14)
    at Module._compile (internal/modules/cjs/loader.js:1139:30) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/user/Discord.RSS/src/web/routes/api/cp.js',
    '/home/user/Discord.RSS/src/web/routes/api/index.js',
    '/home/user/Discord.RSS/src/web/index.js',
    '/home/user/Discord.RSS/src/structs/Client.js',
    '/home/user/Discord.RSS/src/index.js',
    '/home/user/Discord.RSS/server.js'
  ]
}
```
I found that when I made `config.web.enabled` `false`, the bot this time worked, without any problem. So this problem only occures when I'm trying to use the web interface.
So how do I fix this problem? Am I supposed to create the `schedules.js` module/file/script?

**Comment by synzen** [comment]
Hi, dev branch is currently doing a major rewrite and the web UI is broken until that part has been rewritten - see https://github.com/synzen/Discord.RSS/projects/6 for progress. Until then, please use the master branch files as the Setup guide recommends: https://github.com/synzen/Discord.RSS/wiki/Setup

**Comment by StrangeRanger** [comment]
Ok, thank you for letting me know. I actually thought I cloned the master branch, but apparently not.
