### ISSUE TITLE
Cannot find module needle ( linux mint )

### ISSUE THREAD

**Issue by Deflaxz** [synzen/Discord.RSS#16]
node server.js
module.js:472
    throw err;
    ^

Error: Cannot find module 'needle'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/username/Somewhere/request.js:1:78)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by synzen** [comment]
Use `npm install` as instructed on step 2 to install all required packages

**Comment by Deflaxz** [comment]
This have fixed my error thank you for this awesome fast responce.
