### ISSUE TITLE
Bot won't run

### ISSUE THREAD

**Issue by freakyy85** [synzen/Discord.RSS#18]
Hi, it's me again. The bot wont run for me. I get this error:

uwe@baby:~/Discord.RSS$ npm install
uwe@baby:~/Discord.RSS$ nodejs server.js
module.js:471
    throw err;
    ^

Error: Cannot find module '/home/uwe/Discord.RSS/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/uwe/Discord.RSS/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
uwe@baby:~/Discord.RSS$

**Comment by freakyy85** [comment]
wait i tried recreating the bots directory. now i get the following:

uwe@baby:~/Discord.RSS$ npm install
npm WARN discord.js@11.1.0 requires a peer of bufferutil@^3.0.0 but none was installed.
npm WARN discord.js@11.1.0 requires a peer of erlpack@hammerandchisel/erlpack but none was installed.
npm WARN discord.js@11.1.0 requires a peer of node-opus@^0.2.5 but none was installed.
npm WARN discord.js@11.1.0 requires a peer of opusscript@^0.0.3 but none was installed.
npm WARN discord.js@11.1.0 requires a peer of sodium@^2.0.1 but none was installed.
npm WARN discord.js@11.1.0 requires a peer of libsodium-wrappers@^0.5.1 but none was installed.
npm WARN discord.js@11.1.0 requires a peer of uws@^0.14.1 but none was installed.

**Comment by synzen** [comment]
That is fine, you should be able to run it

**Comment by freakyy85** [comment]
ok thanks :)
