### ISSUE TITLE
Bot crashes when server returns response code 520

### ISSUE THREAD

**Issue by Yuri-M-Dias** [synzen/Discord.RSS#25]
From time to time, the bot crashes when receiving a weird server response. This 520 is apparently a [Cloudflare error](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#Cloudflare), but I haven't been able to pinpoint what feed is causing it, or if it's from Discord itself.
Here's what the logs tells me:
```
[22:49:51.113] Fatal Error!
 { Error: unexpected server response (520)
    at ClientRequest._req.on (/usr/src/app/node_modules/ws/lib/WebSocket.js:650:26)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:473:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at TLSSocket.socketOnData (_http_client.js:362:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
  type: 'error',
  target: 
   WebSocket {
     domain: null,
     _events: 
      { message: [Object],
        open: [Object],
        error: [Object],
        close: [Object] },
     _eventsCount: 4,
     _maxListeners: undefined,
     readyState: 0,
     bytesReceived: 0,
     extensions: {},
     protocol: '',
     _binaryType: 'nodebuffer',
     _finalize: [Function: bound finalize],
     _finalizeCalled: false,
     _closeMessage: null,
     _closeTimer: null,
     _closeCode: null,
     _receiver: null,
     _sender: null,
     _socket: null,
     _ultron: null,
     protocolVersion: 13,
     _isServer: false,
     url: 'wss://gateway.discord.gg/?v=6&encoding=json',
     _req: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: true,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedHeader: [Object],
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'GET /?v=6&encoding=json HTTP/1.1\r\nSec-WebSocket-Version: 13\r\nSec-WebSocket-Key: dy6oyrGu+0G23xmcG6+v/g==\r\nConnection: Upgrade\r\nUpgrade: websocket\r
\nSec-WebSocket-Extensions: permessage-deflate; client_max_window_bits\r\nHost: gateway.discord.gg\r\n\r\n',
        _headers: [Object],
        _headerNames: [Object],
        _onPendingData: null,
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '/?v=6&encoding=json',
        _ended: false,
        parser: [Object],
        res: [Object],
        aborted: 1506120591094 } } }

```

**Comment by synzen** [comment]
This unfortunately is on Discord's servers' end. Any errors like this where it completely throws the bot off is related to `discord.js` library that handles API requests to Discord - any feed related errors are handled gracefully and never crashes the bot. The only thing you can do is hope the issue will subside.
