### ISSUE TITLE
Discord.RSS could not login (Error: Incorrect login details were provided.)

### ISSUE THREAD

**Issue by Hostile** [synzen/Discord.RSS#33]
[19:59:49.327] Error: Disconnected from Discord. Attempting to reconnect after ~0.08333333333333333 minutes.
[19:59:49.331] Discord.RSS could not login (Error: Incorrect login details were provided.), retrying in 60 seconds...
[19:59:54.636] Fatal Error!
 Error: Discord.RSS failed to login after 2 attempts.
    at Client.<anonymous> (/root/Discord.RSS/server.js:53:47)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Client.emit (events.js:211:7)
    at WebSocketConnection.onClose (/root/Discord.RSS/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:397:19)
    at WebSocket.onClose (/root/Discord.RSS/node_modules/ws/lib/EventTarget.js:103:16)
    at emitTwo (events.js:126:13)
    at WebSocket.emit (events.js:214:7)
    at WebSocket.emitClose (/root/Discord.RSS/node_modules/ws/lib/WebSocket.js:213:10)
    at _receiver.cleanup (/root/Discord.RSS/node_modules/ws/lib/WebSocket.js:195:41)

**Comment by Hostile** [comment]
fixed it
