### ISSUE TITLE
can yo utell me how to fix this 

### ISSUE THREAD

**Issue by djshylow** [synzen/Discord.RSS#36]
Discord.RSS-2.1.0/server.js:17
    let c = 0
        ^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by synzen** [comment]
What version is your node?

![](https://i.imgur.com/BeRespP.png)
