### ISSUE TITLE
Raspberry Installation

### ISSUE THREAD

**Issue by gamersalpha** [synzen/Discord.RSS#47]
Hello there, 

so i have a raspberry and i m looking how instal on it : 

so i do this step : 

```
sudo apt-get update
sudo mkdir /var/www/html/discordRss
cd /var/www/html/discordRss
sudo git clone https://github.com/synzen/Discord.RSS.git
```
ok and the drama is : 

```

pi@raspberrypi:/var/www/html/discordRss/Discord.RSS $ sudo npm install
npm WARN engine discord.js@11.3.2: wanted: {"node":">=6.0.0"} (current: {"node":"4.8.2","npm":"1.4.21"})
npm WARN package.json jsonify@0.0.0 license should be a valid SPDX license expression
npm WARN package.json sntp@1.0.9 No license field.
npm WARN package.json string_decoder@1.0.3 string_decoder is also the name of a node core module.

> sqlite3@3.1.13 install /var/www/html/discordRss/Discord.RSS/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

/usr/bin/env: « node »: Aucun fichier ou dossier de ce type
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! sqlite3@3.1.13 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 127
npm ERR!
npm ERR! Failed at the sqlite3@3.1.13 install script.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.14.30-v7+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /var/www/html/discordRss/Discord.RSS
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
|
> bufferutil@3.0.4 install /var/www/html/discordRss/Discord.RSS/node_modules/bufferutil
> prebuild-install || node-gyp rebuild

/usr/bin/env: « node »: Aucun fichier ou dossier de ce type
/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:304:16)
ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Linux 4.14.30-v7+
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /var/www/html/discordRss/Discord.RSS/node_modules/bufferutil
gyp ERR! node -v v4.8.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian


> uws@9.14.0 install /var/www/html/discordRss/Discord.RSS/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0


> sodium@2.0.3 preinstall /var/www/html/discordRss/Discord.RSS/node_modules/sodium
> node install.js --preinstall

sh: 1: node: not found
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian


> erlpack@0.1.0 install /var/www/html/discordRss/Discord.RSS/node_modules/erlpack
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:304:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Linux 4.14.30-v7+
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /var/www/html/discordRss/Discord.RSS/node_modules/erlpack
gyp ERR! node -v v4.8.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian


> ref@1.3.5 install /var/www/html/discordRss/Discord.RSS/node_modules/node-opus/node_modules/ogg-packet/node_modules/ref-struct/node_modules/ref
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:304:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Linux 4.14.30-v7+
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /var/www/html/discordRss/Discord.RSS/node_modules/node-opus/node_modules/ogg-packet/node_modules/ref-struct/node_modules/ref
gyp ERR! node -v v4.8.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm WARN optional dep failed, continuing ogg-packet@1.0.0

> node-opus@0.2.7 install /var/www/html/discordRss/Discord.RSS/node_modules/node-opus
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:304:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Linux 4.14.30-v7+
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /var/www/html/discordRss/Discord.RSS/node_modules/node-opus
gyp ERR! node -v v4.8.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/html/discordRss/Discord.RSS/npm-debug.log
npm ERR! not ok code 0
```

do u now what is wrong please

**Comment by Macley-Kun** [comment]
Just curious  but why did you choose that folder?

**Comment by Macley-Kun** [comment]
Its just a bit off for me. Its in a locaties you normally use for websites.

Normally I install it in the default directory (cd ~) . But shouldn’t be a issue.

Synzen advise would fix your issue anyhow.

**Comment by synzen** [comment]
Assuming this is solved after no reply. Feel free to open again.
