### ISSUE TITLE
Unexpected token d in JSON at position 490

### ISSUE THREAD

**Issue by kevle6** [synzen/Discord.RSS#60]
I'm having this issue when starting the bot with `node server.js`. Node version is v8.11.3. 

```
SyntaxError: D:\DiscordBots\DiscordRSS\config.json: Unexpected token d in JSON at position 490
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:671:27)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\DiscordBots\DiscordRSS\util\logger.js:10:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
PS D:\DiscordBots\DiscordRSS>
```

Thanks in advance.

**Comment by synzen** [comment]
Something you changed in config.json made it invalid. If you cannot find the issue I suggest you copy it over again and use https://jsonlint.com/ to make sure everything is formatted correctly. See [here](https://github.com/synzen/Discord.RSS/wiki/Configuration#type-definitions) for type definitions.

**Comment by kevle6** [comment]
Thanks, jsonlint helped find the issue and I managed to fix it. Was just a minor issue with the file directory format for the database in the config.
