### ISSUE TITLE
Requires a peer to install

### ISSUE THREAD

**Issue by traxim** [synzen/Discord.RSS#8]
When i use the command npm install, i get following error

```
npm WARN discord.js@11.0.0 requires a peer of erlpack@hammerandchisel/erlpack#master but none was installed. 
npm WARN discord.js@11.0.0 requires a peer of uws@0.12.0 but none was installed.
```

i install the peers but nothing works. i get the same error.
i used 

```
npm install --save erlpack@hammerandchisel
npm install --save uws@0.12.0
```

Can somebody help me?

**Comment by synzen** [comment]
You can ignore those warnings, just continue on to the next steps

**Comment by traxim** [comment]
Ok thx. But now i get this when i use node rssSever.js

```
[Error: Cannot find module 'node-cmd'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/Discord.RSS/util/feedSchedule.js:12:13)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)](url)
```

**Comment by traxim** [comment]
Ok i searched a solution for my problem with google and i DID it.YES! :)
Thank you so much for the bot!

**Comment by synzen** [comment]
Oh that dependency was a mistake, was something I added for debugging and forgot to remove it when I pushed that commit. I have removed it. Glad it's resolved.
